fishSpecies = {}
fishSpecies['Rock Beauty'] = {
'''
cctttatttactatttggtgcttgagctggaatagtgggaacggctttaagcctgctaat
tcgagcagagctaaaccaaccaggcagcctccttggcgacgaccagatctataatgtcat
cgttacagcacatgcatttgtaataattttttttatggtcatacccgctataattggggg
atttggaaactgactaattcctctaataatcggggcccccgacatggcattcccccgaat
gaataacataagcttttgacttctccctccctcccttctccttcttctagcatccgctgg
ggtagaagctggggccggaactggatgaacagtttacccacccctagcgggtaatctagc
acatgcgggcgcatccgtagatttaaccatcttctcccttcatttagcaggagtttcctc
aattctgggggctattaattttatcacaacgatcatcaatatgaagcctcctgctatctc
tcagtatcaaacacccctatttgtctgagcagtattaatcacagcagtcctactacttct
ttctcttccagttcttgctgcaggtattacaatactcttaacagaccgaaatttaaacac
caccttcttcgaccctgcaggagggggagacccaattctttaccaacacttattc
'''}

fishSpecies['French Angelfish'] = {
'''
cctctatttactatttggtgcttgagccggaatggtaggcactgctttgagcctactaat
tcgagccgagctaaatcaaccgggcagccttctcggagacgaccagatctacaatgttat
cgttacagcacacgcattcgtaataattttttttatggtgatgcccgccatgatcggagg
ctttggaaattgattagtcccactaataattggagccccagacatagcatttcctcgaat
aaataatataagcttttgactcctgcccccttctcttcttcttctccttgcttccgccgg
ggtagaggccggagctggaactgggtgaacagtttacccgcccctagctggcaatctagc
ccacgcaggagcatccgtagacctgaccatcttctccctccacctggccggaatctcctc
aattctaggggctattaactttatcacaaccattattaacataaaaccccctgctatttc
acaataccaaactccactatttgtgtgagctgtcctaattactgcagtgctacttctgct
ttctctccccgtccttgctgccggcatcacaatgcttcttacagaccgaaatcttaatac
tactttctttgaccctgcaggagggggagacccaattctttaccagcacttg
'''
}

fishSpecies['Four Eye Butterfly Fish'] = {
'''
tctctatctagtattcggtgcttgagctgggatagtaggcaccgccttaagtctgctcat
ccgagcagagctcagccagccaggcaccctcctaggcgacgatcagatttataatgtaat
cgttacggcacatgcgttcgtaatgattttctttatagtaataccaattatgattggggg
atttgggaattgactaattcccttaatgattggggctccggacatggccttccctcgaat
gaataacataagcttttgactcctccctccatcctttttcctgcttcttgcctcttctgg
cgtagagtccggggccggcactggatgaacagtttatcctccactagccggtaatctagc
ccatgccggagcatccgttgatctaactatcttctcccttcaccttgcagggatctcctc
cattcttggggctatcaattttattacaacaatcctcaacatgaaaccccctgctatgtc
ccagtatcaaactccccttttcgtctgatctgttctaattacagccgttttacttctctt
gtccctccccgttcttgcagccggaattacaatgcttcttacagaccgaaaccttaatac
aaccttctttgaccctgcagggggcggcgaccccattctttaccaacacctgttc
'''
}

fishSpecies['Blue Tang'] = {
'''
cctttatttagtttttggtgcttgagctgggatagtaggaacggccctaagcctcctaat
ccgggcagaattaagccaaccaggcgccctcctcggagatgatcaaatttataatgtaat
tgttacagcacacgcattcgtaataattttctttatagtaataccaattatgattggtgg
gttcggaaattgattaattccactaatgattggagcccctgacatagcattcccacgaat
aaataacataagcttttgacttttaccaccatctttcctgcttctacttgcatcctctgc
agtagaatctggtgcaggcacaggatgaacagtatacccccctctagccggtaatcttgc
acatgcaggagcatccgtagatctcactattttctccctccacctagcagggatttcttc
aattcttggagctattaattttattacaacaattattaatatgaaacctcctgctatttc
ccaatatcaaacccccctgtttgtatgagcagtactaattaccgccgttctactccttct
ctcacttcctgttctcgctgctggaattacaatactactcacagatcgaaacctgaatac
cactttctttgacccagcaggtggaggagaccccattttatatcaacattta
'''
}

fishSpecies['Yellowtail Snapper'] = {
'''
cctttatctagtatttggtgcctgggccggaatagtaggcacggccctaagcctgctcat
tcgagcagaactaagccagccaggagctcttcttggagacgaccagatttataatgtaat
tgttacagcgcatgcatttgtaataattttctttatagtaataccaatcatgatcggagg
attcgggaactgactgatcccactaatgatcggggcccccgatatggcattccctcgaat
aaataacatgagcttttgactcctcccgccatcattcctattgctactcgcctcttctgg
ggtagaagccggtgctggaactgggtgaacagtttaccctcccctagcaggaaacctagc
acacgcaggagcatctgtagacctaactattttctccctgcatctagcaggtgtttcctc
aattctgggagcaatcaacttcattacaacaatcatcaacatgaaacctcctgccatttc
ccagtatcaaacgcccctattcgtctgagccgtcctaattactgctgttctacttcttct
ctccctaccagttttagcggccggaattacaatgcttcttacagaccgaaatctaaacac
aaccttctttgacccagcaggaggaggggatcccatcctctaccaacatctg
'''
}

fishSpecies['Sargent Major'] = {
'''
cctctatctagtatttggtgcttgagctggaatagtaggaacagccctgagcctccttat
tcgagcagaactaagccaaccaggcgctctcctcggagacgaccagatttacaacgtaat
tgttacggcacatgcctttgtaataattttctttatagtaataccaattataattggagg
gtttggaaactgacttatcccactaatgatcggtgcccctgatatggcattcccccgaat
gaacaatatgagcttctgacttcttcccccatcgttcctacttcttcttgcctcctccgg
agttgaagcaggtgcaggaacaggctgaactgtctacccaccactatcaggcaacctagc
tcacgcaggagcttctgttgacttaactattttctccctccacttagcaggtgtgtcctc
aattttaggagccattaattttattaccactattattaatatgaaacctccagctatttc
tcaataccagactcctctcttcgtatgagccgtactcatcacggccgtgctcctccttct
gtcccttcctgttttagccgctggaattacgatacttctaaccgaccgaaacttaaatac
cacattcttcgacccagctggaggaggagaccccattctttaccaacatttattc
'''
}

fishSpecies['Goliath Grouper'] = {
'''
cctttatcttgtatttggtgcctgggctgggatagtaggaacagcccttagcctactaat
tcgggctgagctaagccagccaggggctctactgggcgatgaccagatctataatgtaat
tgttacagcacatgcttttgtaataatctttttcatagtaatgccaatcatgattggtgg
ctttggaaattgacttgtcccacttataatcggcgcccctgacatagcattccctcgaat
aaataacataagcttctgacttctccccccttctttcctgctccttcttgcctcttcggg
ggtagaagctggtgccggtactggttgaacggtctacccgcccctagccggaaatttagc
ccatgcaggagcatccgtagacttaactattttctcacttcatttagcaggtatctcatc
aattctaggtgcaattaactttattacaaccattattaacataaaaccccctgccatctc
ccaataccaaacacctttgtttgtgtgagctgtactaatcacagcagtactactactcct
ctcccttcccgtccttgccgccggcatcaccatgttgctcactgatcgtaaccttaacac
taccttctttgacccagccggaggaggagatcca
'''
}

fishSpecies['Blue Headed Wrasse'] = {
'''
cctctatcttgtgttcggcgcatgagccgggatagtagggacagccctaagcctgctcat
ccgagcagagttaagccagcccggcgccctccttggggacgatcagatttataacgttat
cgttacagcccacgcattcgtcataattttctttatagtaataccaattatgattggagg
cttcggaaactgactaattcccctaatgattggggcccctgacatggccttccctcggat
gaacaatataagcttctgacttcttccaccctcattccttcttcttctcgcctcctctgg
cgttgaggcaggggccggaactggttggacagtctacccacccctagcagggaaccttgc
ccatgctggtgcatccgttgaccttactattttttcacttcacttggcagggatttcatc
aattctaggtgcaatcaacttcatcacaaccattattaatatgaaacccccagccatctc
ccaatatcaaacgcctcttttcgtatgggctgttctcattacggcagtccttctcctcct
ctcgctcccagtccttgccgctggtattacaatgctcttaacagaccgaaatcttaacac
cactttcttcgaccctgctggagggggggacccaattctttaccaacacctg
'''
}

fishSpecies['Queen Parrotfish'] = {
'''
cctttaccttgtatttggtgcctgagccggaatagtaggcactgccttaagccttctcat
ccgagctgaactaagtcaacccggggcccttctcggagacgaccagatttataatgttat
cgttacagctcatgcatttgtaatgatcttttttatagtcatgcctatcataatcggagg
cttcgggaactgactcatccccctcatgattggggcacctgacatggccttccctcgaat
gaacaatatgagcttctgacttcttcctccctccttcctcctattactcgcctcctctgg
cgtagaagcgggagcaggtaccggatgaaccgtttacccccctctagcaggaaatcttgc
acacgcaggtgcatccgtcgacctaacaattttctctcttcatctagcaggaatttcttc
tatcctaggagcaattaactttattacaacaatcgttaacataaaaccgcctgccatctc
ccaataccaaaccccgctgttcgtatgagctgttttaattactgccgtacttcttctcct
ctcactccctgtcctcgctgcaggaatcacaatgcttctcacagatcgaaatctaaacac
gaccttctttgaccctgcaggcggagganacccaattctttatcaacacctg
'''
}

fishSpecies['Dusky Damselfish'] = {
'''
cctttatctagtatttggtgcctgagccggaatagtaggaacagctctaagtctcctcat
tcgggcagaactaagccaacccggcgctctccttggagacgaccaaatttataatgtaat
tgttacggcacacgcctttgtaataatcttctttatagtaataccaatcatgattggagg
cttcggaaactgacttattcccctaatgatcggggcccccgacatggcctttccccgaat
aaacaatataagcttctgacttctccccccttcctttcttcttctgcttgcctcttcagg
tgtagaagcaggtgcaggaacaggatgaacagtctaccctccactatctggcaacctagc
tcatgcaggggcctccgttgacctaaccattttctcccttcatctagcaggaatttcatc
gatcctaggagcaatcaactttatcactactattattaacatgaagcccccttctatctc
tcaataccaaacccctctctttgtatgagcagttctaatcaccgccgtactactactcct
ctcccttcccgtcttagctgccggtattactatgctcctaacggaccgaaaccttaatac
tactttctttgaccctgcaggaggaggagacccaatcctttaccaacacctt
'''
}


name_cytochrome = {
    'Rock Beauty' : 'Holacanthus Tricolor',
    'French Angelfish' : 'Pomacanthus Paru',
    'Four Eye Butterfly Fish' : 'Chaetodon Capistratus',
    'Blue Tang' : 'Acanthurus Coeruleus',
    'Yellowtail Snapper' : 'Ocyurus Chrysurus',
    'Sargent Major' : 'Abudefduf Saxitilis',
    'Goliath Grouper' : 'Epinephus Itajara',
    'Blue Headed Wrasse' : 'Thalassoma Bifasciatum',
    'Queen Parrotfish' : 'Scarus Vetula',
    'Dusky Damselfish' : 'Stegastes Adustus'
}